# Generated by Django 3.1.7 on 2021-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printF', '0002_auto_20210317_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('password', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=22)),
            ],
        ),
    ]
