# Generated by Django 3.1.7 on 2021-03-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printF', '0003_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userDetails',
            new_name='userDetail',
        ),
    ]
