# Generated by Django 3.1.7 on 2021-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printF', '0004_auto_20210318_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='age',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='month',
            field=models.CharField(default='September', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sex',
            field=models.CharField(default='NONE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='surname',
            field=models.CharField(default='Surname', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='year',
            field=models.CharField(default=1998, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
